version: '2.2'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reservations_service
    expose:
      - "3306"
    ports:
      - "33060:3306"

  reservations-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: reservations-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/reservations-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysql
    links:
      - mysql
    expose:
    - "8090"
    ports:
    - "8090:8090"
